WGBH-MLA/stock-sales-2

app/views/collections/aapb.md, app/views/collections/boston.md, app/views/collections/digital-clips.md, app/views/collections/example-3.md, app/views/collections/example-4.md, app/views/collections/example-5.md, app/views/collections/example-6.md, app/views/collections/frontline.md, app/views/collections/in-the-news.md, app/views/collections/julia-child.md, app/views/collections/music.md, app/views/collections/nova.md, app/views/collections/sports.md, app/views/collections/wgbh-interviews.md, app/views/collections/wgbh-limited-series.md, app/views/home/index.erb, spec/features/homepage_spec.rb
Add cmless markdown pages for each collection.
Add blurbs for each collection.
closes #20, closes #21, closes #24
=> Update textual content

app/assets/stylesheets/blacklight.css.scss, app/assets/stylesheets/colors.css.scss, app/assets/stylesheets/masthead.css.scss, app/assets/stylesheets/navbar.css.scss, app/assets/stylesheets/sidebox.css.scss, app/assets/stylesheets/stock_sales.css.scss, app/assets/stylesheets/utility.css.scss, app/views/home/_masthead.html.erb
A little more toward #29, but mostly just organizing stuff.
=> Separate styles into different files

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/locals/thumb.css.scss, app/views/shared/_thumb_3.html.erb
@afred: please review.
- We don't actually have semibold Witney: It comes out thin if I set that in the CSS.
- The color is the correct dark-blue, as far as I know.
=> Thumbs conform to spec?

app/assets/stylesheets/blacklight.css.scss
=> Darker orange. Fix #52.

app/assets/stylesheets/locals/navbar.css.scss, app/views/shared/_header_navbar.html.erb
=> Make links in navbar match spec. see screengrab.

app/views/about/show.html.erb, app/views/collections/show.html.erb, app/views/home/index.html.erb, config/locales/blacklight.en.yml
=> Better way of doing page titles.

app/views/collections/american-experience.md, app/views/collections/frontline.md, app/views/collections/nova.md
(These are still at full resolution. Avoiding premature optimization, for now.)
=> Images have been uploaded to S3. Fixes #59.

app/assets/stylesheets/globals/fonts.css.scss, app/assets/stylesheets/locals/thumb.css.scss
Using the font inspector, confirmed that we have 400/500/600 Whitney. Grid titles look right. @afred: please review. (Will use the other weights as we need them.)
=> 400/500/600 Whitney

app/assets/stylesheets/locals/about.css.scss, app/controllers/contact_us_controller.rb, app/views/about/contact_us.md, app/views/about/show.html.erb, app/views/contact_us/index.html.erb, app/views/shared/_helpful_links.html.erb, config/routes.rb, spec/features/about_spec.rb, spec/features/collections_spec.rb
@afred: architecture review, please. The contact-us page needs to be a lot like the other "about" pages... but it's different. Is this a good way of doing it?
(tests aren't running for me locally. Separate email.)
=> Rough draft of contact-us form for architecture review.

app/views/collections/_collection_select.html.erb, app/views/collections/show.html.erb
Towards #74. @afred: please review. Works, and we can sort out the style later.
=> Nav select 74

app/views/contact_us/index.html.erb, config/routes.rb
=> Use google form instead of maintaining the mailer ourself.

app/views/collections/aapb.md, app/views/collections/american-experience.md, app/views/collections/boston.md, app/views/collections/frontline.md, app/views/collections/julia-child.md, app/views/collections/music.md, app/views/collections/nova.md, app/views/collections/open-vault.md, app/views/collections/sports.md, app/views/collections/wgbh-limited-series.md
Sometimes it will be wider, sometimes narrower. @afred: please review.
=> We can not force linebreaks in blurbs

app/views/catalog/show.html.erb
Loop over methods. Quick, and good enough for now. Fixes #110; fixes #111; fixes #112. @afred, please review.
=> Clean up labels on details

app/assets/stylesheets/locals/catalog-index.css.scss, app/models/asset.rb, app/views/catalog/_index_header_default.html.erb
@afred: please review. Need to get the actual proxy URLs, and I'm not confident that the UI is quite right. Towards #117.
=> Thumbnail preview play 117

app/assets/stylesheets/locals/catalog-index.css.scss, config/locales/blacklight.en.yml
markup in localization is a little weird, but better than overriding more ERBs?
Fix #118. @afred: please review.
=> arrows only show when links, and no underline.

app/views/home/_masthead.html.erb
Use plain video element until we know we need something more complicated.
Fix #46. @afred: please review.
=> Homepage reel. 

app/assets/stylesheets/globals/colors.css.scss, app/assets/stylesheets/locals/collection.css.scss, app/models/collection.rb, app/views/collections/american-experience.md, app/views/collections/frontline.md, app/views/collections/nova.md, app/views/collections/open-vault.md, app/views/collections/show.html.erb
=> Splash image links 120

app/views/about/help.md, app/views/about/rates.md
=> Fix Markdown: "Main" is required.

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/locals/call_to_action.css.scss, app/assets/stylesheets/locals/search_form.css.scss, app/views/catalog/show.html.erb, app/views/collections/show.html.erb, app/views/shared/_search.html.erb
Parameterizes the placeholder for the search partial.
Isolates search form style.
Closes #150.
=> Adds search form to #show view

app/assets/stylesheets/locals/catalog-index.css.scss
=> Consistent aspect ratio on thumbs. Fix #153.

app/assets/stylesheets/locals/masthead.css.scss
@afred: please review. Towards #83. (Still need two across in tablet... not sure about that.)
=> No extra left padding when narrow.

app/assets/stylesheets/locals/call_to_action.css.scss, app/views/shared/_call_to_action.html.erb, app/views/shared/_search.html.erb
Fix #78. Hopefully it doesn't intersect too much with the other CSS work.
=> Vertical align call-to-action.

scripts/lib/converter.rb
Just now the last API call failed for me, so all the in-memory data was lost. Better to write out the JSON each time. @afred: please review.
=> better to save incrementally

app/assets/stylesheets/locals/catalog-show.css.scss, app/views/catalog/show.html.erb
and worry about tweaking it later. @afred: please review.
=> Just make title bars consistent across the board

app/views/about/help.md
Also made a question from something in ALL CAPS just for consistency with other questions.
@afred please review.
=> Just adding a header above the toc makes it look much better.

app/views/catalog/_home_text.html.erb, config/locales/blacklight.en.yml
=> Fix the no-search-bad-search messaging. (We do not have a left sidebar.)

app/views/shared/_search.html.erb
=> shorter placeholder. Not sure what the point of the comment was?

app/assets/stylesheets/locals/masthead.css.scss
=> Smaller font when medium. Fix #190.

app/assets/stylesheets/locals/collection.css.scss, app/views/collections/show.html.erb
decided that 50/50 did not actually look right. Fix #188. @afred?
=> Collection header tweaks. 

app/assets/stylesheets/locals/thumb.css.scss
=> Size on non-title will fall-back to 14px.

app/assets/stylesheets/locals/call_to_action.css.scss, app/assets/stylesheets/locals/search_form.css.scss, app/views/about/show.html.erb, app/views/collections/show.html.erb, app/views/shared/_search.html.erb
I think this covers all the bases, or at least suggests everything that needs to be checked. Fix #174?
=> input sizing

app/views/catalog/_field_list.html.erb, app/views/catalog/show.html.erb
With more columns, and the lines not necessarily aligning, I think it gets jumbled without the background on the labels... but I'm not fixated on this. @AlisonCSmith : I've just put in a placeholder for your text.
=> New asset layout. Keeping header background for now. Towards #189.

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/globals/flexbox.scss, app/assets/stylesheets/locals/call_to_action.css.scss, app/assets/stylesheets/locals/masthead.css.scss, app/assets/stylesheets/locals/search_form.css.scss, app/views/catalog/_search_header.html.erb, app/views/catalog/_search_header_form_and_contact.html.erb, app/views/catalog/show.html.erb, app/views/shared/_call_to_action.html.erb
=> Call to action styles

app/views/catalog/_index_header_default.html.erb
=> Mutes video in search results

spec/features/collections_spec.rb, spec/spec_helper.rb
* Changes default to check links; requires flag to not check links.
* Fixes buggy Collection pages feature specs.
=> Checks for valid image links in Collection pages.

app/assets/stylesheets/locals/search_form.css.scss, app/views/catalog/_search_header_form_and_contact.html.erb
=> Styles 'contact us' text in search form header.

app/views/collections/nova.md
=> NOVA: caps, links, italics.

app/views/collections/frontline.md
=> frontline caps, italics tweaks.

app/views/collections/american-experience.md
=> amex italics, link.

app/views/collections/open-vault.md
=> Italics and links, mostly.

app/views/collections/aapb.md, app/views/collections/open-vault.md
=> Orange buttons.

app/views/collections/wgbh-limited-series.md
=> Italics, links

app/views/collections/digital-clips.md
=> Lots of broken links fixed. Some formatting.

app/views/collections/music.md
=> Music tweaks

app/views/shared/_call_to_action.html.erb
=> Homepage buttons

app/views/shared/wgbh-logo.svg
=> Fix #221. No hover flicker.

app/views/collections/open-vault.md
@afred?
(More text on the right, and a shorter logo on the left make the alignment seem a little bit off, but I don't want to special case it.)
(copy directly from the OV repo: Already white text with alpha.)
=> openvault logo. Fix #231.

app/views/catalog/_index_header_default.html.erb
=> Clicking now navigates.

app/views/home/_grid.html.erb
=> Apply call_to_action to Collections header. Fix #267.

app/assets/stylesheets/locals/navbar.css.scss
=> Use "!important" instead of specific fragile path. Fix #268.

app/views/contact_us/index.html.erb
@afred? Make it match about/show.erb. (Partial would be overkill?) Fix #281.
=> Increase padding on contact_us. 

app/views/shared/_footer.html.erb
=> Move legalese links up into list. Switch to link_to. Fix #269.

app/controllers/downloads_controller.rb
@afred? Not averse to a longer, more descriptive filename, but the immediate request was just to include the ID, so I didn't want to over-complicate this.
=> Make sure download has good name. Fix #276.

app/assets/stylesheets/locals/catalog-index.css.scss, app/views/catalog/_index_header_default.html.erb
@afred? Feel free to adjust exact pixel count, but looks good to me.
=> Spacing above results links. Fix #279.

app/assets/stylesheets/globals/colors.css.scss, app/assets/stylesheets/locals/catalog-show.css.scss
=> Paler background. Fix #275.

app/views/collections/show.html.erb
=> 3 items per row. Fix #294.

app/views/about/show.html.erb, app/views/collections/show.html.erb, app/views/shared/_helpful_links.html.erb, app/views/shared/_sidebar.html.erb
=> Partial for sidebar. Hide "Helpful Links" if there are none. Fix #272.

app/views/home/_masthead.html.erb
=> Preserve aspect ratio. fix #266.

app/assets/stylesheets/blacklight.css.scss, app/assets/stylesheets/locals/thumb.css.scss
=> Make dark-blue the default for links. Fix #274.

app/assets/stylesheets/locals/collection.css.scss
=> Tweak line-height. Fix #271.

app/assets/stylesheets/locals/catalog-index.css.scss, app/views/catalog/_search_header_form_and_contact.html.erb
Towards #282. @afred: Not sure about the styling goal here: How should it behave if it's too narrow to be in the middle? And how did you actually tweak the CSS for your screen shot?
=> Change wording. Not sure about style.

app/assets/stylesheets/blacklight.css.scss, app/assets/stylesheets/locals/about.css.scss, app/assets/stylesheets/locals/call_to_action.css.scss, app/assets/stylesheets/locals/catalog-index.css.scss, app/assets/stylesheets/locals/navbar.css.scss, app/views/collections/show.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header_navbar.html.erb
@afred? I *think* this covers the bases, w/o bad side effects, but a close look would be good. Fix #261.
=> Left align 261

Gemfile, Gemfile.lock, app/assets/stylesheets/locals/about.css.scss
=> Pretty ToC. Fix #307.

app/assets/stylesheets/locals/collection.css.scss, app/views/shared/_sidebar.html.erb
=> Well around clip search. Fix #273.

app/views/shared/_header_navbar.html.erb
Just a cleanup: Rendering doesn't change. @afred.
=> Seems to render the same. Fix #303.

app/assets/stylesheets/locals/search_form.css.scss
=> Input + button should use full width.

app/assets/javascripts/application.js
=> google analytics. Loads the 1x1 gif on page load.

app/controllers/thumb_controller.rb, config/routes.rb, public/fm_to_csv.xsl, spec/controllers/downloads_controller_spec.rb, spec/controllers/thumb_controller_spec.rb, spec/fixtures/fm-export-results.xml, spec/fixtures/fm-export.csv
@afred?
- Either SD or HD, not both.
- Thumbnail URL.
=> Better export

config/environments/production.rb
Per this issue on Uglifier: https://github.com/lautis/uglifier/issues/127
=> Enables ES6 Syntax with Uglifier
